import ROOT

#---------------- *Open the ROOT files and get the histogram from each file* ----------

file = ROOT.TFile("/home/msahil/work/madgraph/MG5_aMC_v2_9_15/template_tttxtx_wminus_fullyHadronic_signal/Events/run_01_decayed_1/TMVAMulticlassification.root", "READ")
directory = file.Get("dataset/InputVariables_Id")


#------------------------------------leading Jets-------------------------------------------
jet0_h1 = directory.Get("jet1_pt__Signal_Id")
jet0_h2 = directory.Get("jet1_pt__tt~_Id")
jet0_h3 = directory.Get("jet1_pt__tt~H_Id")
jet0_h4 = directory.Get("jet1_pt__tt~W_Id")
jet0_h5 = directory.Get("jet1_pt__tt~Z_Id")
jet0_h6 = directory.Get("jet1_pt__tt~tb~_Id")
jet0_h7 = directory.Get("jet1_pt__tt~tW-_Id")
jet0_h8 = directory.Get("jet1_pt__tt~t~w+_Id")

#Scale the histograms by the cross sections
factor = 1.0
jet0_h1.Scale(factor/jet0_h1.Integral())
jet0_h2.Scale(factor/jet0_h2.Integral())
jet0_h3.Scale(factor/jet0_h3.Integral())
jet0_h4.Scale(factor/jet0_h4.Integral())
jet0_h5.Scale(factor/jet0_h5.Integral())
jet0_h6.Scale(factor/jet0_h6.Integral())
jet0_h7.Scale(factor/jet0_h7.Integral())
jet0_h8.Scale(factor/jet0_h8.Integral())

#Create a new canvas and draw the histograms
canvas1 = ROOT.TCanvas("canvas1", "Leading Jet Pt", 800, 600)
jet0_h1.SetLineColor(ROOT.kBlack)
jet0_h2.SetFillColor(ROOT.kCyan-10)
jet0_h3.SetFillColor(ROOT.kCyan-8)
jet0_h4.SetFillColor(ROOT.kCyan-5)
jet0_h5.SetFillColor(ROOT.kYellow-8)
jet0_h6.SetFillColor(ROOT.kRed-4)
jet0_h7.SetFillColor(ROOT.kRed-5)
jet0_h8.SetFillColor(ROOT.kYellow+1)

jet0_h1.SetLineWidth(2)
jet0_h2.SetStats(0)
jet0_h2.SetTitle("Leading Jet P_{T}")
jet0_h2.GetXaxis().SetTitle("Pt_{j1} [GeV]")
jet0_h2.GetYaxis().SetTitle("Normalized")
#jet0_h2.GetYaxis().SetRangeUser(0,0.25)
#jet0_h2.GetXaxis().SetRangeUser(0, 700)

jet0_h2.Draw("hist")
jet0_h3.Draw("hist same")
jet0_h4.Draw("hist same")
jet0_h5.Draw("hist same")
jet0_h6.Draw("hist same")
jet0_h7.Draw("hist same")
jet0_h8.Draw("hist same")
jet0_h1.Draw("hist same")

tex1 = ROOT.TLatex(0.153,0.92,"t#bar{t}t#bar{t}W Signal")
tex1.SetNDC()
tex1.SetTextAngle(0)
tex1.SetTextFont(42)
tex1.SetTextSize(0.04)
tex1.SetTextAlign(11)
tex1.Draw()

tex2 = ROOT.TLatex(0.730,0.92,"\sqrt{S} = {13TeV}")
tex2.SetNDC()
tex2.SetTextAngle(0)
tex2.SetTextFont(42)
tex2.SetTextAlign(11)
tex2.SetTextSize(0.04)
tex2.Draw()

legend1 = ROOT.TLegend(0.7, 0.7, 0.9, 0.85)
legend1.AddEntry(jet0_h1, "t#bar{t}t#bar{t}W", "l")
legend1.AddEntry(jet0_h2, "t#bar{t}", "f")
legend1.AddEntry(jet0_h3, "t#bar{t}H", "f")
legend1.AddEntry(jet0_h4, "t#bar{t}W", "f")
legend1.AddEntry(jet0_h5, "t#bar{t}Z", "f")
legend1.AddEntry(jet0_h6, "t#bar{t}t#bar{b}", "f")
legend1.AddEntry(jet0_h7, "t#bar{t}tW^{-}", "f")
legend1.AddEntry(jet0_h8, "t#bar{t}#bar{t}W^{+}", "f")
legend1.SetBorderSize(0)
legend1.Draw()

#canvas1.SetLogy()
canvas1.Draw()
canvas1.SaveAs("tmva_bdt_variables_plots/leading_jet_Pt.png")

#----------------------------------2nd Leading Jets-----------------------------------
jet1_h1 = directory.Get("jet2_pt__Signal_Id")
jet1_h2 = directory.Get("jet2_pt__tt~_Id")
jet1_h3 = directory.Get("jet2_pt__tt~H_Id")
jet1_h4 = directory.Get("jet2_pt__tt~W_Id")
jet1_h5 = directory.Get("jet2_pt__tt~Z_Id")
jet1_h6 = directory.Get("jet2_pt__tt~tb~_Id")
jet1_h7 = directory.Get("jet2_pt__tt~tW-_Id")
jet1_h8 = directory.Get("jet2_pt__tt~t~w+_Id")

#Scale the histograms by the cross sections
factor = 1.0
jet1_h1.Scale(factor/jet1_h1.Integral())
jet1_h2.Scale(factor/jet1_h2.Integral())
jet1_h3.Scale(factor/jet1_h3.Integral())
jet1_h4.Scale(factor/jet1_h4.Integral())
jet1_h5.Scale(factor/jet1_h5.Integral())
jet1_h6.Scale(factor/jet1_h6.Integral())
jet1_h7.Scale(factor/jet1_h7.Integral())
jet1_h8.Scale(factor/jet1_h8.Integral())

#Create a new canvas and draw the histograms
canvas2 = ROOT.TCanvas("canvas2", "2nd Leading Jet Pt", 800, 600)
jet1_h1.SetLineColor(ROOT.kBlack)
jet1_h2.SetFillColor(ROOT.kCyan-10)
jet1_h3.SetFillColor(ROOT.kCyan-8)
jet1_h4.SetFillColor(ROOT.kCyan-5)
jet1_h5.SetFillColor(ROOT.kYellow-8)
jet1_h6.SetFillColor(ROOT.kRed-4)
jet1_h7.SetFillColor(ROOT.kRed-5)
jet1_h8.SetFillColor(ROOT.kYellow+1)

jet1_h1.SetLineWidth(2)
jet1_h2.SetStats(0)
jet1_h2.SetTitle("2nd Leading Jet P_{T}")
jet1_h2.GetXaxis().SetTitle("Pt_{j2} [GeV]")
jet1_h2.GetYaxis().SetTitle("Normalized")
#jet1_h2.GetYaxis().SetRangeUser(0,0.40)
#jet1_h2.GetXaxis().SetRangeUser(0, 400)

jet1_h2.Draw("hist")
jet1_h3.Draw("hist same")
jet1_h4.Draw("hist same")
jet1_h5.Draw("hist same")
jet1_h6.Draw("hist same")
jet1_h7.Draw("hist same")
jet1_h8.Draw("hist same")
jet1_h1.Draw("hist same")

tex3 = ROOT.TLatex(0.153,0.92,"t#bar{t}t#bar{t}W Signal")
tex3.SetNDC()
tex3.SetTextAngle(0)
tex3.SetTextFont(42)
tex3.SetTextSize(0.04)
tex3.SetTextAlign(11)
tex3.Draw()

tex4 = ROOT.TLatex(0.730,0.92,"\sqrt{S} = {13TeV}")
tex4.SetNDC()
tex4.SetTextAngle(0)
tex4.SetTextFont(42)
tex4.SetTextAlign(11)
tex4.SetTextSize(0.04)
tex4.Draw()

legend2 = ROOT.TLegend(0.7, 0.7, 0.9, 0.85)
legend2.AddEntry(jet1_h1, "t#bar{t}t#bar{t}W", "l")
legend2.AddEntry(jet1_h2, "t#bar{t}", "f")
legend2.AddEntry(jet1_h3, "t#bar{t}H", "f")
legend2.AddEntry(jet1_h4, "t#bar{t}W", "f")
legend2.AddEntry(jet1_h5, "t#bar{t}Z", "f")
legend2.AddEntry(jet1_h6, "t#bar{t}t#bar{b}", "f")
legend2.AddEntry(jet1_h7, "t#bar{t}tW^{-}", "f")
legend2.AddEntry(jet1_h8, "t#bar{t}#bar{t}W^{+}", "f")
legend2.SetBorderSize(0)
legend2.Draw()

#canvas2.SetLogy()
canvas2.Draw()
canvas2.SaveAs("tmva_bdt_variables_plots/2nd_leading_jet_Pt.png")

#-----------------------------------------3rd Leading Jets--------------------------
jet2_h1 = directory.Get("jet3_pt__Signal_Id")
jet2_h2 = directory.Get("jet3_pt__tt~_Id")
jet2_h3 = directory.Get("jet3_pt__tt~H_Id")
jet2_h4 = directory.Get("jet3_pt__tt~W_Id")
jet2_h5 = directory.Get("jet3_pt__tt~Z_Id")
jet2_h6 = directory.Get("jet3_pt__tt~tb~_Id")
jet2_h7 = directory.Get("jet3_pt__tt~tW-_Id")
jet2_h8 = directory.Get("jet3_pt__tt~t~w+_Id")

#Scale the histograms by the cross sections
factor = 1.0
jet2_h1.Scale(factor/jet2_h1.Integral())
jet2_h2.Scale(factor/jet2_h2.Integral())
jet2_h3.Scale(factor/jet2_h3.Integral())
jet2_h4.Scale(factor/jet2_h4.Integral())
jet2_h5.Scale(factor/jet2_h5.Integral())
jet2_h6.Scale(factor/jet2_h6.Integral())
jet2_h7.Scale(factor/jet2_h7.Integral())
jet2_h8.Scale(factor/jet2_h8.Integral())

#Create a new canvas and draw the histograms
canvas3 = ROOT.TCanvas("canvas3", "3rd Leading Jet Pt", 800, 600)
jet2_h1.SetLineColor(ROOT.kBlack)
jet2_h2.SetFillColor(ROOT.kCyan-10)
jet2_h3.SetFillColor(ROOT.kCyan-8)
jet2_h4.SetFillColor(ROOT.kCyan-5)
jet2_h5.SetFillColor(ROOT.kYellow-8)
jet2_h6.SetFillColor(ROOT.kRed-4)
jet2_h7.SetFillColor(ROOT.kRed-5)
jet2_h8.SetFillColor(ROOT.kYellow+1)

jet2_h1.SetLineWidth(2)
jet2_h2.SetStats(0)
jet2_h2.SetTitle("3rd Leading Jet P_{T}")
jet2_h2.GetXaxis().SetTitle("Pt_{j3} [GeV]")
jet2_h2.GetYaxis().SetTitle("Normalized")
#jet2_h2.GetYaxis().SetRangeUser(0,0.30)
#jet2_h2.GetXaxis().SetRangeUser(0, 300)

jet2_h2.Draw("hist")
jet2_h3.Draw("hist same")
jet2_h4.Draw("hist same")
jet2_h5.Draw("hist same")
jet2_h6.Draw("hist same")
jet2_h7.Draw("hist same")
jet2_h8.Draw("hist same")
jet2_h1.Draw("hist same")

tex5 = ROOT.TLatex(0.153,0.92,"t#bar{t}t#bar{t}W Signal")
tex5.SetNDC()
tex5.SetTextAngle(0)
tex5.SetTextFont(42)
tex5.SetTextSize(0.04)
tex5.SetTextAlign(11)
tex5.Draw()

tex6 = ROOT.TLatex(0.730,0.92,"\sqrt{S} = {13TeV}")
tex6.SetNDC()
tex6.SetTextAngle(0)
tex6.SetTextFont(42)
tex6.SetTextAlign(11)
tex6.SetTextSize(0.04)
tex6.Draw()

legend3 = ROOT.TLegend(0.7, 0.7, 0.9, 0.85)
legend3.AddEntry(jet2_h1, "t#bar{t}t#bar{t}W", "l")
legend3.AddEntry(jet2_h2, "t#bar{t}", "f")
legend3.AddEntry(jet2_h3, "t#bar{t}H", "f")
legend3.AddEntry(jet2_h4, "t#bar{t}W", "f")
legend3.AddEntry(jet2_h5, "t#bar{t}Z", "f")
legend3.AddEntry(jet1_h6, "t#bar{t}t#bar{b}", "f")
legend3.AddEntry(jet1_h7, "t#bar{t}tW^{-}", "f")
legend3.AddEntry(jet1_h8, "t#bar{t}#bar{t}W^{+}", "f")
legend3.SetBorderSize(0)
legend3.Draw()

canvas3.Draw()
canvas3.SaveAs("tmva_bdt_variables_plots/3rd_leading_jet_Pt.png")

#-------------------------------------------4th Leading Jets--------------------------
jet3_h1 = directory.Get("jet4_pt__Signal_Id")
jet3_h2 = directory.Get("jet4_pt__tt~_Id")
jet3_h3 = directory.Get("jet4_pt__tt~H_Id")
jet3_h4 = directory.Get("jet4_pt__tt~W_Id")
jet3_h5 = directory.Get("jet4_pt__tt~Z_Id")
jet3_h6 = directory.Get("jet4_pt__tt~tb~_Id")
jet3_h7 = directory.Get("jet4_pt__tt~tW-_Id")
jet3_h8 = directory.Get("jet4_pt__tt~t~w+_Id")

#Scale the histograms by the cross sections
factor = 1.0
jet3_h1.Scale(factor/jet3_h1.Integral())
jet3_h2.Scale(factor/jet3_h2.Integral())
jet3_h3.Scale(factor/jet3_h3.Integral())
jet3_h4.Scale(factor/jet3_h4.Integral())
jet3_h5.Scale(factor/jet3_h5.Integral())
jet3_h6.Scale(factor/jet3_h6.Integral())
jet3_h7.Scale(factor/jet3_h7.Integral())
jet3_h8.Scale(factor/jet3_h8.Integral())

#Create a new canvas and draw the histograms
canvas4 = ROOT.TCanvas("canvas4", "4th Leading Jet Pt", 800, 600)
jet3_h1.SetLineColor(ROOT.kBlack)
jet3_h2.SetFillColor(ROOT.kCyan-10)
jet3_h3.SetFillColor(ROOT.kCyan-8)
jet3_h4.SetFillColor(ROOT.kCyan-5)
jet3_h5.SetFillColor(ROOT.kYellow-8)
jet3_h6.SetFillColor(ROOT.kRed-4)
jet3_h7.SetFillColor(ROOT.kRed-5)
jet3_h8.SetFillColor(ROOT.kYellow+1)

jet3_h1.SetLineWidth(2)
jet3_h2.SetStats(0)
jet3_h2.SetTitle("4th Leading Jet P_{T}")
jet3_h2.GetXaxis().SetTitle("Pt_{j4} [GeV]")
jet3_h2.GetYaxis().SetTitle("Normalized")
#jet3_h2.GetYaxis().SetRangeUser(0,0.50)
#jet3_h2.GetXaxis().SetRangeUser(0, 250)

jet3_h2.Draw("hist")
jet3_h3.Draw("hist same")
jet3_h4.Draw("hist same")
jet3_h5.Draw("hist same")
jet3_h6.Draw("hist same")
jet3_h7.Draw("hist same")
jet3_h8.Draw("hist same")
jet3_h1.Draw("hist same")

tex7 = ROOT.TLatex(0.153,0.92,"t#bar{t}t#bar{t}W Signal")
tex7.SetNDC()
tex7.SetTextAngle(0)
tex7.SetTextFont(42)
tex7.SetTextSize(0.04)
tex7.SetTextAlign(11)
tex7.Draw()

tex8 = ROOT.TLatex(0.730,0.92,"\sqrt{S} = {13TeV}")
tex8.SetNDC()
tex8.SetTextAngle(0)
tex8.SetTextFont(42)
tex8.SetTextAlign(11)
tex8.SetTextSize(0.04)
tex8.Draw()

legend4 = ROOT.TLegend(0.7, 0.7, 0.9, 0.85)
legend4.AddEntry(jet3_h1, "t#bar{t}t#bar{t}W", "l")
legend4.AddEntry(jet3_h2, "t#bar{t}", "f")
legend4.AddEntry(jet3_h3, "t#bar{t}H", "f")
legend4.AddEntry(jet3_h4, "t#bar{t}W", "f")
legend4.AddEntry(jet3_h5, "t#bar{t}Z", "f")
legend4.AddEntry(jet1_h6, "t#bar{t}t#bar{b}", "f")
legend4.AddEntry(jet1_h7, "t#bar{t}tW^{-}", "f")
legend4.AddEntry(jet1_h8, "t#bar{t}#bar{t}W^{+}", "f")
legend4.SetBorderSize(0)
legend4.Draw()

canvas4.Draw()
canvas4.SaveAs("tmva_bdt_variables_plots/4th_leading_jet_Pt.png")
"""
#--------------------------------------------5th Leading Jets---------------------------
jet4_h1 = fIn1.Get("jet_pt_4")
jet4_h2 = fIn2.Get("jet_pt_4")
jet4_h3 = fIn3.Get("jet_pt_4")
jet4_h4 = fIn4.Get("jet_pt_4")
jet4_h5 = fIn5.Get("jet_pt_4")
jet4_h6 = fIn6.Get("jet_pt_4")
jet4_h7 = fIn7.Get("jet_pt_4")
jet4_h8 = fIn8.Get("jet_pt_4")
jet4_h9 = fIn9.Get("jet_pt_4")

#Scale the histograms by the cross sections
factor = 1.0
jet4_h1.Scale(factor/jet4_h1.Integral())
jet4_h2.Scale(factor/jet4_h2.Integral())
jet4_h3.Scale(factor/jet4_h3.Integral())
jet4_h4.Scale(factor/jet4_h4.Integral())
jet4_h5.Scale(factor/jet4_h5.Integral())
jet4_h6.Scale(factor/jet4_h6.Integral())
jet4_h7.Scale(factor/jet4_h7.Integral())
jet4_h8.Scale(factor/jet4_h8.Integral())
jet4_h9.Scale(factor/jet4_h9.Integral())


#Create a new canvas and draw the histograms
canvas5 = ROOT.TCanvas("canvas5", "5th Leading Jet Pt", 800, 600)
jet4_h1.SetLineColor(ROOT.kBlack)
jet4_h2.SetFillColor(ROOT.kCyan-10)
jet4_h3.SetFillColor(ROOT.kCyan-8)
jet4_h4.SetFillColor(ROOT.kCyan-5)
jet4_h5.SetFillColor(ROOT.kYellow-8)
jet4_h6.SetFillColor(ROOT.kRed-4)
jet4_h7.SetFillColor(ROOT.kRed-5)
jet4_h8.SetFillColor(ROOT.kYellow+1)
jet4_h9.SetFillColor(ROOT.kCyan-6)

jet4_h1.SetLineWidth(2)
jet4_h2.SetStats(0)
jet4_h2.SetTitle("5th Leading Jet P_{T}")
jet4_h2.GetXaxis().SetTitle("Pt_{j5} [GeV]")
jet4_h2.GetYaxis().SetTitle("Normalized")
jet4_h2.GetYaxis().SetRangeUser(0, 0.50)
jet4_h2.GetXaxis().SetRangeUser(0, 200)

jet4_h2.Draw("hist")
jet4_h3.Draw("hist same")
jet4_h4.Draw("hist same")
jet4_h5.Draw("hist same")
jet4_h6.Draw("hist same")
jet4_h7.Draw("hist same")
jet4_h8.Draw("hist same")
jet4_h9.Draw("hist same")
jet4_h1.Draw("hist same")

tex9 = ROOT.TLatex(0.153,0.92,"t#bar{t}t#bar{t}W Signal")
tex9.SetNDC()
tex9.SetTextAngle(0)
tex9.SetTextFont(42)
tex9.SetTextSize(0.04)
tex9.SetTextAlign(11)
tex9.Draw()

tex10 = ROOT.TLatex(0.730,0.92,"\sqrt{S} = {13TeV}")
tex10.SetNDC()
tex10.SetTextAngle(0)
tex10.SetTextFont(42)
tex10.SetTextAlign(11)
tex10.SetTextSize(0.04)
tex10.Draw()

legend5 = ROOT.TLegend(0.7, 0.7, 0.9, 0.85)
legend5.AddEntry(jet4_h1, "t#bar{t}t#bar{t}W", "l")
legend5.AddEntry(jet4_h2, "t#bar{t}", "f")
legend5.AddEntry(jet4_h3, "t#bar{t}Z", "f")
legend5.AddEntry(jet4_h4, "WZ", "f")
legend5.AddEntry(jet4_h5, "t#bar{t}H", "f")
legend5.AddEntry(jet4_h6, "t#bar{t}W", "f")
legend5.AddEntry(jet1_h7, "t#bar{t}t#bar{b}", "f")
legend5.AddEntry(jet1_h8, "t#bar{t}tW^{-}", "f")
legend5.AddEntry(jet1_h9, "t#bar{t}#bar{t}W^{+}", "f")
legend5.SetBorderSize(0)
legend5.Draw()

canvas5.Draw()
canvas5.SaveAs("bdt_variables_plots/5th_leading_jet_Pt.png.png")

#-----------------------------------6th Leading Jets---------------------------------
jet5_h1 = fIn1.Get("jet_pt_5")
jet5_h2 = fIn2.Get("jet_pt_5")
jet5_h3 = fIn3.Get("jet_pt_5")
jet5_h4 = fIn4.Get("jet_pt_5")
jet5_h5 = fIn5.Get("jet_pt_5")
jet5_h6 = fIn6.Get("jet_pt_5")
jet5_h7 = fIn7.Get("jet_pt_5")
jet5_h8 = fIn8.Get("jet_pt_5")
jet5_h9 = fIn9.Get("jet_pt_5")

#Scale the histograms by the cross sections
factor = 1.0
jet5_h1.Scale(factor/jet5_h1.Integral())
jet5_h2.Scale(factor/jet5_h2.Integral())
jet5_h3.Scale(factor/jet5_h3.Integral())
jet5_h4.Scale(factor/jet5_h4.Integral())
jet5_h5.Scale(factor/jet5_h5.Integral())
jet5_h6.Scale(factor/jet5_h6.Integral())
jet5_h7.Scale(factor/jet5_h7.Integral())
jet5_h8.Scale(factor/jet5_h8.Integral())
jet5_h9.Scale(factor/jet5_h9.Integral())


#Create a new canvas and draw the histograms
canvas6 = ROOT.TCanvas("canvas6", "6th Leading Jet Pt", 800, 600)
jet5_h1.SetLineColor(ROOT.kBlack)
jet5_h2.SetFillColor(ROOT.kCyan-10)
jet5_h3.SetFillColor(ROOT.kCyan-8)
jet5_h4.SetFillColor(ROOT.kCyan-5)
jet5_h5.SetFillColor(ROOT.kYellow-8)
jet5_h6.SetFillColor(ROOT.kRed-4)
jet5_h7.SetFillColor(ROOT.kRed-5)
jet5_h8.SetFillColor(ROOT.kYellow+1)
jet5_h9.SetFillColor(ROOT.kCyan-6)

jet5_h1.SetLineWidth(2)
jet5_h2.SetStats(0)
jet5_h2.SetTitle("6th Leading Jet P_{T}")
jet5_h2.GetXaxis().SetTitle("Pt_{j6} [GeV]")
jet5_h2.GetYaxis().SetTitle("Normalized")
jet5_h2.GetYaxis().SetRangeUser(0, 0.70)
jet5_h2.GetXaxis().SetRangeUser(0, 200)

jet5_h2.Draw("hist")
jet5_h3.Draw("hist same")
jet5_h4.Draw("hist same")
jet5_h5.Draw("hist same")
jet5_h6.Draw("hist same")
jet5_h7.Draw("hist same")
jet5_h8.Draw("hist same")
jet5_h9.Draw("hist same")
jet5_h1.Draw("hist same")

tex11 = ROOT.TLatex(0.153,0.92,"t#bar{t}t#bar{t}W Signal")
tex11.SetNDC()
tex11.SetTextAngle(0)
tex11.SetTextFont(42)
tex11.SetTextSize(0.04)
tex11.SetTextAlign(11)
tex11.Draw()

tex12 = ROOT.TLatex(0.730,0.92,"\sqrt{S} = {13TeV}")
tex12.SetNDC()
tex12.SetTextAngle(0)
tex12.SetTextFont(42)
tex12.SetTextAlign(11)
tex12.SetTextSize(0.04)
tex12.Draw()

legend6 = ROOT.TLegend(0.7, 0.7, 0.9, 0.85)
legend6.AddEntry(jet5_h1, "t#bar{t}t#bar{t}W", "l")
legend6.AddEntry(jet5_h2, "t#bar{t}", "f")
legend6.AddEntry(jet5_h3, "t#bar{t}Z", "f")
legend6.AddEntry(jet5_h4, "WZ", "f")
legend6.AddEntry(jet5_h5, "t#bar{t}H", "f")
legend6.AddEntry(jet5_h6, "t#bar{t}W", "f")
legend6.AddEntry(jet1_h7, "t#bar{t}t#bar{b}", "f")
legend6.AddEntry(jet1_h8, "t#bar{t}tW^{-}", "f")
legend6.AddEntry(jet1_h9, "t#bar{t}#bar{t}W^{+}", "f")
legend6.SetBorderSize(0)
legend6.Draw()

canvas6.Draw()
canvas6.SaveAs("bdt_variables_plots/6th_leading_jet_Pt.png")
"""


#-------------------------------------------Leading B-Jets------------------------------------
b_jet0_h1 = directory.Get("bjet1_pt__Signal_Id")
b_jet0_h2 = directory.Get("bjet1_pt__tt~_Id")
b_jet0_h3 = directory.Get("bjet1_pt__tt~H_Id")
b_jet0_h4 = directory.Get("bjet1_pt__tt~W_Id")
b_jet0_h5 = directory.Get("bjet1_pt__tt~Z_Id")
b_jet0_h6 = directory.Get("bjet1_pt__tt~tb~_Id")
b_jet0_h7 = directory.Get("bjet1_pt__tt~tW-_Id")
b_jet0_h8 = directory.Get("bjet1_pt__tt~t~w+_Id")

#Scale the histograms by the cross sections
factor = 1.0
b_jet0_h1.Scale(factor/b_jet0_h1.Integral())
b_jet0_h2.Scale(factor/b_jet0_h2.Integral())
b_jet0_h3.Scale(factor/b_jet0_h3.Integral())
b_jet0_h4.Scale(factor/b_jet0_h4.Integral())
b_jet0_h5.Scale(factor/b_jet0_h5.Integral())
b_jet0_h6.Scale(factor/b_jet0_h6.Integral())
b_jet0_h7.Scale(factor/b_jet0_h7.Integral())
b_jet0_h8.Scale(factor/b_jet0_h8.Integral())

#Create a new canvas and draw the histograms
canvas7 = ROOT.TCanvas("canvas7", "Leading B-Jets Pt", 800, 600)
b_jet0_h1.SetLineColor(ROOT.kBlack)
b_jet0_h2.SetFillColor(ROOT.kCyan-10)
b_jet0_h3.SetFillColor(ROOT.kCyan-8)
b_jet0_h4.SetFillColor(ROOT.kYellow-8)
b_jet0_h5.SetFillColor(ROOT.kRed-4)
b_jet0_h6.SetFillColor(ROOT.kRed-5)
b_jet0_h7.SetFillColor(ROOT.kYellow+1)
b_jet0_h8.SetFillColor(ROOT.kCyan-6)

b_jet0_h1.SetLineWidth(2)
b_jet0_h2.SetStats(0)
b_jet0_h2.SetTitle("Leading b-jet P_{T}")
b_jet0_h2.GetXaxis().SetTitle("Pt_{bj} [GeV]")
b_jet0_h2.GetYaxis().SetTitle("Normalized")
#b_jet0_h2.GetYaxis().SetRangeUser(0,0.14)
#b_jet0_h2.GetXaxis().SetRangeUser(0,400)

b_jet0_h2.Draw("hist")
b_jet0_h3.Draw("hist same")
b_jet0_h4.Draw("hist same")
b_jet0_h5.Draw("hist same")
b_jet0_h6.Draw("hist same")
b_jet0_h7.Draw("hist same")
b_jet0_h8.Draw("hist same")
b_jet0_h1.Draw("hist same")

tex13 = ROOT.TLatex(0.153,0.92,"t#bar{t}t#bar{t}W Signal")
tex13.SetNDC()
tex13.SetTextAngle(0)
tex13.SetTextFont(42)
tex13.SetTextSize(0.04)
tex13.SetTextAlign(11)
tex13.Draw()

tex14 = ROOT.TLatex(0.730,0.92,"\sqrt{S} = {13TeV}")
tex14.SetNDC()
tex14.SetTextAngle(0)
tex14.SetTextFont(42)
tex14.SetTextAlign(11)
tex14.SetTextSize(0.04)
tex14.Draw()

legend7 = ROOT.TLegend(0.7, 0.7, 0.9, 0.85)
legend7.AddEntry(b_jet0_h1, "t#bar{t}t#bar{t}W", "l")
legend7.AddEntry(b_jet0_h2, "t#bar{t}", "f")
legend7.AddEntry(b_jet0_h3, "t#bar{t}H", "f")
legend7.AddEntry(b_jet0_h4, "t#bar{t}W", "f")
legend7.AddEntry(b_jet0_h5, "t#bar{t}Z", "f")
legend7.AddEntry(b_jet0_h6, "t#bar{t}t#bar{b}", "f")
legend7.AddEntry(b_jet0_h7, "t#bar{t}tW^{-}", "f")
legend7.AddEntry(b_jet0_h8, "t#bar{t}#bar{t}W^{+}", "f")
legend7.SetBorderSize(0)
legend7.Draw()

canvas7.Draw()
canvas7.SaveAs("tmva_bdt_variables_plots/1st_leading_bjet_Pt.png")

#-----------------------------------------Scalar HT---------------------------------------
Scalar_h1 = directory.Get("Scalar_HT__Signal_Id")
Scalar_h2 = directory.Get("Scalar_HT__tt~_Id")
Scalar_h3 = directory.Get("Scalar_HT__tt~H_Id")
Scalar_h4 = directory.Get("Scalar_HT__tt~W_Id")
Scalar_h5 = directory.Get("Scalar_HT__tt~Z_Id")
Scalar_h6 = directory.Get("Scalar_HT__tt~tb~_Id")
Scalar_h7 = directory.Get("Scalar_HT__tt~tW-_Id")
Scalar_h8 = directory.Get("Scalar_HT__tt~t~w+_Id")

#Scale the histograms by the cross sections
factor = 1.0
Scalar_h1.Scale(factor/Scalar_h1.Integral())
Scalar_h2.Scale(factor/Scalar_h2.Integral())
Scalar_h3.Scale(factor/Scalar_h3.Integral())
Scalar_h4.Scale(factor/Scalar_h4.Integral())
Scalar_h5.Scale(factor/Scalar_h5.Integral())
Scalar_h6.Scale(factor/Scalar_h6.Integral())
Scalar_h7.Scale(factor/Scalar_h7.Integral())
Scalar_h8.Scale(factor/Scalar_h8.Integral())

#Create a new canvas and draw the histograms
canvas8 = ROOT.TCanvas("canvas8", "Scalar HT", 800, 600)
Scalar_h1.SetLineColor(ROOT.kBlack)
Scalar_h2.SetFillColor(ROOT.kCyan-10)
Scalar_h3.SetFillColor(ROOT.kCyan-8)
Scalar_h4.SetFillColor(ROOT.kCyan-5)
Scalar_h5.SetFillColor(ROOT.kYellow-8)
Scalar_h6.SetFillColor(ROOT.kRed-4)
Scalar_h7.SetFillColor(ROOT.kRed-5)
Scalar_h8.SetFillColor(ROOT.kYellow+1)

Scalar_h1.SetLineWidth(2)
Scalar_h2.SetStats(0)
Scalar_h2.SetTitle("Scalar HT")
Scalar_h2.GetXaxis().SetTitle("HT [GeV]")
Scalar_h2.GetYaxis().SetTitle("Normalized")
#Scalar_h2.GetYaxis().SetRangeUser(0,0.50)
#Scalar_h2.GetXaxis().SetRangeUser(0, 2000)

Scalar_h2.Draw("hist")
Scalar_h3.Draw("hist same")
Scalar_h4.Draw("hist same")
Scalar_h5.Draw("hist same")
Scalar_h6.Draw("hist same")
Scalar_h7.Draw("hist same")
Scalar_h8.Draw("hist same")
Scalar_h1.Draw("hist same")

tex15 = ROOT.TLatex(0.153,0.92,"t#bar{t}t#bar{t}W Signal")
tex15.SetNDC()
tex15.SetTextAngle(0)
tex15.SetTextFont(42)
tex15.SetTextSize(0.04)
tex15.SetTextAlign(11)
tex15.Draw()

tex16 = ROOT.TLatex(0.730,0.92,"\sqrt{S} = {13TeV}")
tex16.SetNDC()
tex16.SetTextAngle(0)
tex16.SetTextFont(42)
tex16.SetTextAlign(11)
tex16.SetTextSize(0.04)
tex16.Draw()

legend8 = ROOT.TLegend(0.7, 0.7, 0.9, 0.85)
legend8.AddEntry(Scalar_h1, "t#bar{t}t#bar{t}W", "l")
legend8.AddEntry(Scalar_h2, "t#bar{t}", "f")
legend8.AddEntry(Scalar_h3, "t#bar{t}Z", "f")
legend8.AddEntry(Scalar_h4, "t#bar{t}H", "f")
legend8.AddEntry(Scalar_h5, "t#bar{t}W", "f")
legend8.AddEntry(Scalar_h6, "t#bar{t}t#bar{b}", "f")
legend8.AddEntry(Scalar_h7, "t#bar{t}tW^{-}", "f")
legend8.AddEntry(Scalar_h8, "t#bar{t}#bar{t}W^{+}", "f")
legend8.SetBorderSize(0)
legend8.Draw()

canvas8.Draw()
canvas8.SaveAs("tmva_bdt_variables_plots/Scalar_HT.png")

#--------------------------------------Sum of Pt of B-Jets-------------------------
bjets_h1 = directory.Get("sumbjet_pt__Signal_Id")
bjets_h2 = directory.Get("sumbjet_pt__tt~_Id")
bjets_h3 = directory.Get("sumbjet_pt__tt~H_Id")
bjets_h4 = directory.Get("sumbjet_pt__tt~W_Id")
bjets_h5 = directory.Get("sumbjet_pt__tt~Z_Id")
bjets_h6 = directory.Get("sumbjet_pt__tt~tb~_Id")
bjets_h7 = directory.Get("sumbjet_pt__tt~tW-_Id")
bjets_h8 = directory.Get("sumbjet_pt__tt~t~w+_Id")

#Scale the histograms by the cross sections
factor = 1.0
bjets_h1.Scale(factor/bjets_h1.Integral())
bjets_h2.Scale(factor/bjets_h2.Integral())
bjets_h3.Scale(factor/bjets_h3.Integral())
bjets_h4.Scale(factor/bjets_h4.Integral())
bjets_h5.Scale(factor/bjets_h5.Integral())
bjets_h6.Scale(factor/bjets_h6.Integral())
bjets_h7.Scale(factor/bjets_h7.Integral())
bjets_h8.Scale(factor/bjets_h8.Integral())

#Create a new canvas and draw the histograms
canvas9 = ROOT.TCanvas("canvas9", "#sum Pt of B-Jets", 800, 600)
bjets_h1.SetLineColor(ROOT.kBlack)
bjets_h2.SetFillColor(ROOT.kCyan-10)
bjets_h3.SetFillColor(ROOT.kCyan-8)
bjets_h4.SetFillColor(ROOT.kCyan-5)
bjets_h5.SetFillColor(ROOT.kYellow-8)
bjets_h6.SetFillColor(ROOT.kRed-5)
bjets_h7.SetFillColor(ROOT.kYellow+1)
bjets_h8.SetFillColor(ROOT.kCyan-6)

bjets_h1.SetLineWidth(2)
bjets_h2.SetStats(0)
bjets_h2.SetTitle("SumP_{T} b-jets")
bjets_h2.GetXaxis().SetTitle("#sumPt_{bj} [GeV]")
bjets_h2.GetYaxis().SetTitle("Normalized")
#bjets_h2.GetYaxis().SetRangeUser(0,0.20)
#bjets_h2.GetXaxis().SetRangeUser(0,1000)

bjets_h2.Draw("hist")
bjets_h3.Draw("hist same")
bjets_h4.Draw("hist same")
bjets_h5.Draw("hist same")
bjets_h6.Draw("hist same")
bjets_h7.Draw("hist same")
bjets_h8.Draw("hist same")
bjets_h1.Draw("hist same")

tex17 = ROOT.TLatex(0.153,0.92,"t#bar{t}t#bar{t}W Signal")
tex17.SetNDC()
tex17.SetTextAngle(0)
tex17.SetTextFont(42)
tex17.SetTextSize(0.04)
tex17.SetTextAlign(11)
tex17.Draw()

tex18 = ROOT.TLatex(0.730,0.92,"\sqrt{S} = {13TeV}")
tex18.SetNDC()
tex18.SetTextAngle(0)
tex18.SetTextFont(42)
tex18.SetTextAlign(11)
tex18.SetTextSize(0.04)
tex18.Draw()

legend9 = ROOT.TLegend(0.7, 0.7, 0.9, 0.85)
legend9.AddEntry(bjets_h1, "t#bar{t}t#bar{t}W", "l")
legend9.AddEntry(bjets_h2, "t#bar{t}", "f")
legend9.AddEntry(bjets_h3, "t#bar{t}H", "f")
legend9.AddEntry(bjets_h4, "t#bar{t}W", "f")
legend9.AddEntry(bjets_h5, "t#bar{t}Z", "f")
legend9.AddEntry(bjets_h6, "t#bar{t}t#bar{b}", "f")
legend9.AddEntry(bjets_h7, "t#bar{t}tW^{-}", "f")
legend9.AddEntry(bjets_h8, "t#bar{t}#bar{t}W^{+}", "f")
legend9.SetBorderSize(0)
legend9.Draw()

canvas9.Draw()
canvas9.SaveAs("tmva_bdt_variables_plots/sum_Pt_bjets.png")

#----------------------------------------Number of Jets----------------------------
N_jets_h1 = directory.Get("numJets__Signal_Id")
N_jets_h2 = directory.Get("numJets__tt~_Id")
N_jets_h3 = directory.Get("numJets__tt~H_Id")
N_jets_h4 = directory.Get("numJets__tt~W_Id")
N_jets_h5 = directory.Get("numJets__tt~Z_Id")
N_jets_h6 = directory.Get("numJets__tt~tb~_Id")
N_jets_h7 = directory.Get("numJets__tt~tW-_Id")
N_jets_h8 = directory.Get("numJets__tt~t~w+_Id")

#Scale the histograms by the cross sections
factor = 1.0
N_jets_h1.Scale(factor/N_jets_h1.Integral())
N_jets_h2.Scale(factor/N_jets_h2.Integral())
N_jets_h3.Scale(factor/N_jets_h3.Integral())
N_jets_h4.Scale(factor/N_jets_h4.Integral())
N_jets_h5.Scale(factor/N_jets_h5.Integral())
N_jets_h6.Scale(factor/N_jets_h6.Integral())
N_jets_h7.Scale(factor/N_jets_h7.Integral())
N_jets_h8.Scale(factor/N_jets_h8.Integral())

#Create a new canvas and draw the histograms
canvas10 = ROOT.TCanvas("canvas10", "Number of Jets", 800, 600)
N_jets_h1.SetLineColor(ROOT.kBlack)
N_jets_h2.SetFillColor(ROOT.kCyan-10)
N_jets_h3.SetFillColor(ROOT.kCyan-8)
N_jets_h4.SetFillColor(ROOT.kCyan-5)
N_jets_h5.SetFillColor(ROOT.kYellow-8)
N_jets_h6.SetFillColor(ROOT.kRed-4)
N_jets_h7.SetFillColor(ROOT.kRed-5)
N_jets_h8.SetFillColor(ROOT.kYellow+1)

N_jets_h1.SetLineWidth(2)
N_jets_h2.SetStats(0)
N_jets_h2.SetTitle("Number of Jets")
N_jets_h2.GetXaxis().SetTitle("N_{j}")
N_jets_h2.GetYaxis().SetTitle("Normalized")
#N_jets_h2.GetYaxis().SetRangeUser(0, 0.50)
#N_jets_h2.GetXaxis().SetRangeUser(5.0, 16.0)

N_jets_h2.Draw("hist")
N_jets_h3.Draw("hist same")
N_jets_h4.Draw("hist same")
N_jets_h5.Draw("hist same")
N_jets_h6.Draw("hist same")
N_jets_h7.Draw("hist same")
N_jets_h8.Draw("hist same")
N_jets_h1.Draw("hist same")

tex19 = ROOT.TLatex(0.153,0.92,"t#bar{t}t#bar{t}W Signal")
tex19.SetNDC()
tex19.SetTextAngle(0)
tex19.SetTextFont(42)
tex19.SetTextSize(0.04)
tex19.SetTextAlign(11)
tex19.Draw()

tex20 = ROOT.TLatex(0.730,0.92,"\sqrt{S} = {13TeV}")
tex20.SetNDC()
tex20.SetTextAngle(0)
tex20.SetTextFont(42)
tex20.SetTextAlign(11)
tex20.SetTextSize(0.04)
tex20.Draw()

legend10 = ROOT.TLegend(0.7, 0.7, 0.9, 0.85)
legend10.AddEntry(N_jets_h1, "t#bar{t}t#bar{t}W", "l")
legend10.AddEntry(N_jets_h2, "t#bar{t}", "f")
legend10.AddEntry(N_jets_h3, "t#bar{t}H", "f")
legend10.AddEntry(N_jets_h4, "t#bar{t}W", "f")
legend10.AddEntry(N_jets_h5, "t#bar{t}Z", "f")
legend10.AddEntry(N_jets_h6, "t#bar{t}t#bar{b}", "f")
legend10.AddEntry(N_jets_h7, "t#bar{t}tW^{-}", "f")
legend10.AddEntry(N_jets_h8, "t#bar{t}#bar{t}W^{+}", "f")
legend10.SetBorderSize(0)
legend10.Draw()

canvas10.Draw()
canvas10.SaveAs("tmva_bdt_variables_plots/number_jets.png")

#-------------------------------------------Number of B-Jets---------------------------
N_bjets_h1 = directory.Get("numBJets__Signal_Id")
N_bjets_h2 = directory.Get("numBJets__tt~_Id")
N_bjets_h3 = directory.Get("numBJets__tt~H_Id")
N_bjets_h4 = directory.Get("numBJets__tt~W_Id")
N_bjets_h5 = directory.Get("numBJets__tt~Z_Id")
N_bjets_h6 = directory.Get("numBJets__tt~tb~_Id")
N_bjets_h7 = directory.Get("numBJets__tt~tW-_Id")
N_bjets_h8 = directory.Get("numBJets__tt~t~w+_Id")

#Scale the histograms by the cross sections
factor = 1.0
N_bjets_h1.Scale(factor/N_bjets_h1.Integral())
N_bjets_h2.Scale(factor/N_bjets_h2.Integral())
N_bjets_h3.Scale(factor/N_bjets_h3.Integral())
N_bjets_h4.Scale(factor/N_bjets_h4.Integral())
N_bjets_h5.Scale(factor/N_bjets_h5.Integral())
N_bjets_h6.Scale(factor/N_bjets_h6.Integral())
N_bjets_h7.Scale(factor/N_bjets_h7.Integral())
N_bjets_h8.Scale(factor/N_bjets_h8.Integral())

#Create a new canvas and draw the histograms
canvas11 = ROOT.TCanvas("canvas11", "Number of B-Jets", 800, 600)
N_bjets_h1.SetLineColor(ROOT.kBlack)
N_bjets_h2.SetFillColor(ROOT.kCyan-10)
N_bjets_h3.SetFillColor(ROOT.kCyan-8)
N_bjets_h4.SetFillColor(ROOT.kCyan-5)
N_bjets_h5.SetFillColor(ROOT.kYellow-8)
N_bjets_h6.SetFillColor(ROOT.kRed-5)
N_bjets_h7.SetFillColor(ROOT.kYellow+1)
N_bjets_h8.SetFillColor(ROOT.kCyan-6)


N_bjets_h1.SetLineWidth(2)
N_bjets_h2.SetStats(0)
N_bjets_h2.SetTitle("Number of B-Jets")
N_bjets_h2.GetXaxis().SetTitle("N_{bj}")
N_bjets_h2.GetYaxis().SetTitle("Normalized")
#N_bjets_h2.GetYaxis().SetRangeUser(0,0.50)

N_bjets_h2.Draw("hist")
N_bjets_h3.Draw("hist same")
N_bjets_h4.Draw("hist same")
N_bjets_h5.Draw("hist same")
N_bjets_h6.Draw("hist same")
N_bjets_h7.Draw("hist same")
N_bjets_h8.Draw("hist same")
N_bjets_h1.Draw("hist same")

tex21 = ROOT.TLatex(0.153,0.92,"t#bar{t}t#bar{t}W Signal")
tex21.SetNDC()
tex21.SetTextAngle(0)
tex21.SetTextFont(42)
tex21.SetTextSize(0.04)
tex21.SetTextAlign(11)
tex21.Draw()

tex22 = ROOT.TLatex(0.730,0.92,"\sqrt{S} = {13TeV}")
tex22.SetNDC()
tex22.SetTextAngle(0)
tex22.SetTextFont(42)
tex22.SetTextAlign(11)
tex22.SetTextSize(0.04)
tex22.Draw()

legend11 = ROOT.TLegend(0.7, 0.7, 0.9, 0.85)
legend11.AddEntry(N_bjets_h1, "t#bar{t}t#bar{t}W", "l")
legend11.AddEntry(N_bjets_h2, "t#bar{t}", "f")
legend11.AddEntry(N_bjets_h3, "t#bar{t}H", "f")
legend11.AddEntry(N_bjets_h4, "t#bar{t}W", "f")
legend11.AddEntry(N_bjets_h5, "t#bar{t}Z", "f")
legend11.AddEntry(N_bjets_h6, "t#bar{t}t#bar{b}", "f")
legend11.AddEntry(N_bjets_h7, "t#bar{t}tW^{-}", "f")
legend11.AddEntry(N_bjets_h8, "t#bar{t}#bar{t}W^{+}", "f")
legend11.SetBorderSize(0)
legend11.Draw()

canvas11.Draw()
canvas11.SaveAs("tmva_bdt_variables_plots/number_bjets.png")

#----------------------------------------Delta Eta of Jets--------------------------------
hdEta_j_h1 = directory.Get("deltaEta_jets__Signal_Id")
hdEta_j_h2 = directory.Get("deltaEta_jets__tt~_Id")
hdEta_j_h3 = directory.Get("deltaEta_jets__tt~H_Id")
hdEta_j_h4 = directory.Get("deltaEta_jets__tt~W_Id")
hdEta_j_h5 = directory.Get("deltaEta_jets__tt~Z_Id")
hdEta_j_h6 = directory.Get("deltaEta_jets__tt~tb~_Id")
hdEta_j_h7 = directory.Get("deltaEta_jets__tt~tW-_Id")
hdEta_j_h8 = directory.Get("deltaEta_jets__tt~t~w+_Id")

#Scale the histograms by the cross sections
factor = 1.0
hdEta_j_h1.Scale(factor/hdEta_j_h1.Integral())
hdEta_j_h2.Scale(factor/hdEta_j_h2.Integral())
hdEta_j_h3.Scale(factor/hdEta_j_h3.Integral())
hdEta_j_h4.Scale(factor/hdEta_j_h4.Integral())
hdEta_j_h5.Scale(factor/hdEta_j_h5.Integral())
hdEta_j_h6.Scale(factor/hdEta_j_h6.Integral())
hdEta_j_h7.Scale(factor/hdEta_j_h7.Integral())
hdEta_j_h8.Scale(factor/hdEta_j_h8.Integral())

#Create a new canvas and draw the histograms
canvas12 = ROOT.TCanvas("canvas12", "#Delta#eta Jets", 800, 600)
hdEta_j_h1.SetLineColor(ROOT.kBlack)
hdEta_j_h2.SetFillColor(ROOT.kCyan-10)
hdEta_j_h3.SetFillColor(ROOT.kCyan-8)
hdEta_j_h4.SetFillColor(ROOT.kCyan-5)
hdEta_j_h5.SetFillColor(ROOT.kYellow-8)
hdEta_j_h6.SetFillColor(ROOT.kRed-4)
hdEta_j_h7.SetFillColor(ROOT.kRed-5)
hdEta_j_h8.SetFillColor(ROOT.kYellow+1)


hdEta_j_h1.SetLineWidth(2)
hdEta_j_h2.SetStats(0)
hdEta_j_h2.SetTitle("#Delta#eta Jets")
hdEta_j_h2.GetXaxis().SetTitle("#Delta#eta_{j}")
hdEta_j_h2.GetYaxis().SetTitle("Normalized")
hdEta_j_h2.GetYaxis().SetRangeUser(0, 0.2)

hdEta_j_h2.Draw("hist")
hdEta_j_h3.Draw("hist same")
hdEta_j_h4.Draw("hist same")
hdEta_j_h5.Draw("hist same")
hdEta_j_h6.Draw("hist same")
hdEta_j_h7.Draw("hist same")
hdEta_j_h8.Draw("hist same")
hdEta_j_h1.Draw("hist same")

tex23 = ROOT.TLatex(0.153,0.92,"t#bar{t}t#bar{t}W Signal")
tex23.SetNDC()
tex23.SetTextAngle(0)
tex23.SetTextFont(42)
tex23.SetTextSize(0.04)
tex23.SetTextAlign(11)
tex23.Draw()

tex24 = ROOT.TLatex(0.730,0.92,"\sqrt{S} = {13TeV}")
tex24.SetNDC()
tex24.SetTextAngle(0)
tex24.SetTextFont(42)
tex24.SetTextAlign(11)
tex24.SetTextSize(0.04)
tex24.Draw()

legend12 = ROOT.TLegend(0.7, 0.7, 0.9, 0.85)
legend12.AddEntry(hdEta_j_h1, "t#bar{t}t#bar{t}W", "l")
legend12.AddEntry(hdEta_j_h2, "t#bar{t}", "f")
legend12.AddEntry(hdEta_j_h3, "t#bar{t}H", "f")
legend12.AddEntry(hdEta_j_h4, "t#bar{t}W", "f")
legend12.AddEntry(hdEta_j_h5, "t#bar{t}Z", "f")
legend12.AddEntry(hdEta_j_h6, "t#bar{t}t#bar{b}", "f")
legend12.AddEntry(hdEta_j_h7, "t#bar{t}tW^{-}", "f")
legend12.AddEntry(hdEta_j_h8, "t#bar{t}#bar{t}W^{+}", "f")
legend12.SetBorderSize(0)
legend12.Draw()

canvas12.Draw()
canvas12.SaveAs("tmva_bdt_variables_plots/deltaEat_jets.png")

#-------------------------------------Delta Phi of Jets------------------------------
hdphi_j_h1 = directory.Get("deltaPhi_jets__Signal_Id")
hdphi_j_h2 = directory.Get("deltaPhi_jets__tt~_Id")
hdphi_j_h3 = directory.Get("deltaPhi_jets__tt~H_Id")
hdphi_j_h4 = directory.Get("deltaPhi_jets__tt~W_Id")
hdphi_j_h5 = directory.Get("deltaPhi_jets__tt~Z_Id")
hdphi_j_h6 = directory.Get("deltaPhi_jets__tt~tb~_Id")
hdphi_j_h7 = directory.Get("deltaPhi_jets__tt~tW-_Id")
hdphi_j_h8 = directory.Get("deltaPhi_jets__tt~t~w+_Id")

#Scale the histograms by the cross sections
factor = 1.0
hdphi_j_h1.Scale(factor/hdphi_j_h1.Integral())
hdphi_j_h2.Scale(factor/hdphi_j_h2.Integral())
hdphi_j_h3.Scale(factor/hdphi_j_h3.Integral())
hdphi_j_h4.Scale(factor/hdphi_j_h4.Integral())
hdphi_j_h5.Scale(factor/hdphi_j_h5.Integral())
hdphi_j_h6.Scale(factor/hdphi_j_h6.Integral())
hdphi_j_h7.Scale(factor/hdphi_j_h7.Integral())
hdphi_j_h8.Scale(factor/hdphi_j_h8.Integral())

#Create a new canvas and draw the histograms
canvas13 = ROOT.TCanvas("canvas13", "#Delta#phi Jets", 800, 600)
hdphi_j_h1.SetLineColor(ROOT.kBlack)
hdphi_j_h2.SetFillColor(ROOT.kCyan-10)
hdphi_j_h3.SetFillColor(ROOT.kCyan-8)
hdphi_j_h4.SetFillColor(ROOT.kCyan-5)
hdphi_j_h5.SetFillColor(ROOT.kYellow-8)
hdphi_j_h6.SetFillColor(ROOT.kRed-4)
hdphi_j_h7.SetFillColor(ROOT.kRed-5)
hdphi_j_h8.SetFillColor(ROOT.kYellow+1)

hdphi_j_h1.SetLineWidth(2)
hdphi_j_h2.SetStats(0)
hdphi_j_h2.SetTitle("#Delta#phi Jets")
hdphi_j_h2.GetXaxis().SetTitle("#Delta#phi_{j}")
hdphi_j_h2.GetYaxis().SetTitle("Normalized")
hdphi_j_h2.GetYaxis().SetRangeUser(0, 0.15)

hdphi_j_h2.Draw("hist")
hdphi_j_h3.Draw("hist same")
hdphi_j_h4.Draw("hist same")
hdphi_j_h5.Draw("hist same")
hdphi_j_h6.Draw("hist same")
hdphi_j_h7.Draw("hist same")
hdphi_j_h8.Draw("hist same")
hdphi_j_h1.Draw("hist same")

tex25 = ROOT.TLatex(0.153,0.92,"t#bar{t}t#bar{t}W Signal")
tex25.SetNDC()
tex25.SetTextAngle(0)
tex25.SetTextFont(42)
tex25.SetTextSize(0.04)
tex25.SetTextAlign(11)
tex25.Draw()

tex26 = ROOT.TLatex(0.730,0.92,"\sqrt{S} = {13TeV}")
tex26.SetNDC()
tex26.SetTextAngle(0)
tex26.SetTextFont(42)
tex26.SetTextAlign(11)
tex26.SetTextSize(0.04)
tex26.Draw()

legend13 = ROOT.TLegend(0.7, 0.7, 0.9, 0.85)
legend13.AddEntry(hdphi_j_h1, "t#bar{t}t#bar{t}W", "l")
legend13.AddEntry(hdphi_j_h2, "t#bar{t}", "f")
legend13.AddEntry(hdphi_j_h3, "t#bar{t}Z", "f")
legend13.AddEntry(hdphi_j_h4, "t#bar{t}H", "f")
legend13.AddEntry(hdphi_j_h5, "t#bar{t}W", "f")
legend13.AddEntry(hdphi_j_h6, "t#bar{t}t#bar{b}", "f")
legend13.AddEntry(hdphi_j_h7, "t#bar{t}tW^{-}", "f")
legend13.AddEntry(hdphi_j_h8, "t#bar{t}#bar{t}W^{+}", "f")
legend13.SetBorderSize(0)
legend13.Draw()

canvas13.Draw()
canvas13.SaveAs("tmva_bdt_variables_plots/deltaPhi_jets.png")

#----------------------------------------Delta Eta of B-Jets--------------------------------
hdEta_bj_h1 = directory.Get("deltaEta_bjets__Signal_Id")
hdEta_bj_h2 = directory.Get("deltaEta_bjets__tt~_Id")
hdEta_bj_h3 = directory.Get("deltaEta_bjets__tt~H_Id")
hdEta_bj_h4 = directory.Get("deltaEta_bjets__tt~W_Id")
hdEta_bj_h5 = directory.Get("deltaEta_bjets__tt~Z_Id")
hdEta_bj_h6 = directory.Get("deltaEta_bjets__tt~tb~_Id")
hdEta_bj_h7 = directory.Get("deltaEta_bjets__tt~tW-_Id")
hdEta_bj_h8 = directory.Get("deltaEta_bjets__tt~t~w+_Id")

#Scale the histograms by the cross sections
factor = 1.0
hdEta_bj_h1.Scale(factor/hdEta_bj_h1.Integral())
hdEta_bj_h2.Scale(factor/hdEta_bj_h2.Integral())
hdEta_bj_h3.Scale(factor/hdEta_bj_h3.Integral())
hdEta_bj_h4.Scale(factor/hdEta_bj_h4.Integral())
hdEta_bj_h5.Scale(factor/hdEta_bj_h5.Integral())
hdEta_bj_h6.Scale(factor/hdEta_bj_h6.Integral())
hdEta_bj_h7.Scale(factor/hdEta_bj_h7.Integral())
hdEta_bj_h8.Scale(factor/hdEta_bj_h8.Integral())

#Create a new canvas and draw the histograms
canvas14 = ROOT.TCanvas("canvas14", "#Delta#eta B-Jets", 800, 600)
hdEta_bj_h1.SetLineColor(ROOT.kBlack)
hdEta_bj_h2.SetFillColor(ROOT.kCyan-10)
hdEta_bj_h3.SetFillColor(ROOT.kCyan-8)
hdEta_bj_h4.SetFillColor(ROOT.kCyan-5)
hdEta_bj_h5.SetFillColor(ROOT.kYellow-8)
hdEta_bj_h6.SetFillColor(ROOT.kRed-5)
hdEta_bj_h7.SetFillColor(ROOT.kYellow+1)
hdEta_bj_h8.SetFillColor(ROOT.kCyan-6)

hdEta_bj_h1.SetLineWidth(2)
hdEta_bj_h2.SetStats(0)
hdEta_bj_h2.SetTitle("#Delta#eta B-Jets")
hdEta_bj_h2.GetXaxis().SetTitle("#Delta#eta_{bj}")
hdEta_bj_h2.GetYaxis().SetTitle("Normalized")
hdEta_bj_h2.GetYaxis().SetRangeUser(0,0.15)

hdEta_bj_h2.Draw("hist")
hdEta_bj_h3.Draw("hist same")
hdEta_bj_h4.Draw("hist same")
hdEta_bj_h5.Draw("hist same")
hdEta_bj_h6.Draw("hist same")
hdEta_bj_h7.Draw("hist same")
hdEta_bj_h8.Draw("hist same")
hdEta_bj_h1.Draw("hist same")

tex27 = ROOT.TLatex(0.153,0.92,"t#bar{t}t#bar{t}W Signal")
tex27.SetNDC()
tex27.SetTextAngle(0)
tex27.SetTextFont(42)
tex27.SetTextSize(0.04)
tex27.SetTextAlign(11)
tex27.Draw()

tex28 = ROOT.TLatex(0.730,0.92,"\sqrt{S} = {13TeV}")
tex28.SetNDC()
tex28.SetTextAngle(0)
tex28.SetTextFont(42)
tex28.SetTextAlign(11)
tex28.SetTextSize(0.04)
tex28.Draw()

legend14 = ROOT.TLegend(0.7, 0.7, 0.9, 0.85)
legend14.AddEntry(hdEta_bj_h1, "t#bar{t}t#bar{t}W", "l")
legend14.AddEntry(hdEta_bj_h2, "t#bar{t}", "f")
legend14.AddEntry(hdEta_bj_h3, "t#bar{t}H", "f")
legend14.AddEntry(hdEta_bj_h4, "t#bar{t}W", "f")
legend14.AddEntry(hdEta_bj_h5, "t#bar{t}Z", "f")
legend14.AddEntry(hdEta_bj_h6, "t#bar{t}t#bar{b}", "f")
legend14.AddEntry(hdEta_bj_h7, "t#bar{t}tW^{-}", "f")
legend14.AddEntry(hdEta_bj_h8, "t#bar{t}#bar{t}W^{+}", "f")

legend14.SetBorderSize(0)
legend14.Draw()

canvas14.Draw()
canvas14.SaveAs("tmva_bdt_variables_plots/deltaEta_bjets.png")

#----------------------------------------Delta Phi of B-Jets--------------------------------
hdphi_bj_h1 = directory.Get("deltaPhi_bjets__Signal_Id")
hdphi_bj_h2 = directory.Get("deltaPhi_bjets__tt~_Id")
hdphi_bj_h3 = directory.Get("deltaPhi_bjets__tt~H_Id")
hdphi_bj_h4 = directory.Get("deltaPhi_bjets__tt~W_Id")
hdphi_bj_h5 = directory.Get("deltaPhi_bjets__tt~Z_Id")
hdphi_bj_h6 = directory.Get("deltaPhi_bjets__tt~tb~_Id")
hdphi_bj_h7 = directory.Get("deltaPhi_bjets__tt~tW-_Id")
hdphi_bj_h8 = directory.Get("deltaPhi_bjets__tt~t~w+_Id")

#Scale the histograms by the cross sections
factor = 1.0
hdphi_bj_h1.Scale(factor/hdphi_bj_h1.Integral())
hdphi_bj_h2.Scale(factor/hdphi_bj_h2.Integral())
hdphi_bj_h3.Scale(factor/hdphi_bj_h3.Integral())
hdphi_bj_h4.Scale(factor/hdphi_bj_h4.Integral())
hdphi_bj_h5.Scale(factor/hdphi_bj_h5.Integral())
hdphi_bj_h6.Scale(factor/hdphi_bj_h6.Integral())
hdphi_bj_h7.Scale(factor/hdphi_bj_h7.Integral())
hdphi_bj_h8.Scale(factor/hdphi_bj_h8.Integral())

#Create a new canvas and draw the histograms
canvas15 = ROOT.TCanvas("canvas15", "#Delta#phi B-Jets", 800, 600)
hdphi_bj_h1.SetLineColor(ROOT.kBlack)
hdphi_bj_h2.SetFillColor(ROOT.kCyan-10)
hdphi_bj_h3.SetFillColor(ROOT.kCyan-8)
hdphi_bj_h4.SetFillColor(ROOT.kCyan-5)
hdphi_bj_h5.SetFillColor(ROOT.kYellow-8)
hdphi_bj_h6.SetFillColor(ROOT.kRed-5)
hdphi_bj_h7.SetFillColor(ROOT.kYellow+1)
hdphi_bj_h8.SetFillColor(ROOT.kCyan-6)

hdphi_bj_h1.SetLineWidth(2)
hdphi_bj_h2.SetStats(0)
hdphi_bj_h2.SetTitle("#Delta#phi B-Jets")
hdphi_bj_h2.GetXaxis().SetTitle("#Delta#phi_{bj}")
hdphi_bj_h2.GetYaxis().SetTitle("Normalized")
hdphi_bj_h2.GetYaxis().SetRangeUser(0,0.15)
hdphi_bj_h2.GetXaxis().SetRangeUser(-6.0, 6.0)

hdphi_bj_h2.Draw("hist")
hdphi_bj_h3.Draw("hist same")
hdphi_bj_h4.Draw("hist same")
hdphi_bj_h5.Draw("hist same")
hdphi_bj_h6.Draw("hist same")
hdphi_bj_h7.Draw("hist same")
hdphi_bj_h8.Draw("hist same")
hdphi_bj_h1.Draw("hist same")

tex29 = ROOT.TLatex(0.153,0.92,"t#bar{t}t#bar{t}W Signal")
tex29.SetNDC()
tex29.SetTextAngle(0)
tex29.SetTextFont(42)
tex29.SetTextSize(0.04)
tex29.SetTextAlign(11)
tex29.Draw()

tex30 = ROOT.TLatex(0.730,0.92,"\sqrt{S} = {13TeV}")
tex30.SetNDC()
tex30.SetTextAngle(0)
tex30.SetTextFont(42)
tex30.SetTextAlign(11)
tex30.SetTextSize(0.04)
tex30.Draw()

legend15 = ROOT.TLegend(0.7, 0.7, 0.9, 0.85)
legend15.AddEntry(hdphi_bj_h1, "t#bar{t}t#bar{t}W", "l")
legend15.AddEntry(hdphi_bj_h2, "t#bar{t}", "f")
legend15.AddEntry(hdphi_bj_h3, "t#bar{t}H", "f")
legend15.AddEntry(hdphi_bj_h4, "t#bar{t}W", "f")
legend15.AddEntry(hdphi_bj_h5, "t#bar{t}Z", "f")
legend15.AddEntry(hdphi_bj_h6, "t#bar{t}t#bar{b}", "f")
legend15.AddEntry(hdphi_bj_h7, "t#bar{t}tW^{-}", "f")
legend15.AddEntry(hdphi_bj_h8, "t#bar{t}#bar{t}W^{+}", "f")
legend15.SetBorderSize(0)
legend15.Draw()

canvas15.Draw()
canvas15.SaveAs("tmva_bdt_variables_plots/deltaPhi_bjets.png")

#----------------------------------------Delta R of Jets--------------------------------
hdR_j_h1 = directory.Get("deltaR_jets__Signal_Id")
hdR_j_h2 = directory.Get("deltaR_jets__tt~_Id")
hdR_j_h3 = directory.Get("deltaR_jets__tt~H_Id")
hdR_j_h4 = directory.Get("deltaR_jets__tt~W_Id")
hdR_j_h5 = directory.Get("deltaR_jets__tt~Z_Id")
hdR_j_h6 = directory.Get("deltaR_jets__tt~tb~_Id")
hdR_j_h7 = directory.Get("deltaR_jets__tt~tW-_Id")
hdR_j_h8 = directory.Get("deltaR_jets__tt~t~w+_Id")

#Scale the histograms by the cross sections
factor = 1.0
hdR_j_h1.Scale(factor/hdR_j_h1.Integral())
hdR_j_h2.Scale(factor/hdR_j_h2.Integral())
hdR_j_h3.Scale(factor/hdR_j_h3.Integral())
hdR_j_h4.Scale(factor/hdR_j_h4.Integral())
hdR_j_h5.Scale(factor/hdR_j_h5.Integral())
hdR_j_h6.Scale(factor/hdR_j_h6.Integral())
hdR_j_h7.Scale(factor/hdR_j_h7.Integral())
hdR_j_h8.Scale(factor/hdR_j_h8.Integral())

#Create a new canvas and draw the histograms
canvas16 = ROOT.TCanvas("canvas16", "#DeltaR Jets", 800, 600)
hdR_j_h1.SetLineColor(ROOT.kBlack)
hdR_j_h2.SetFillColor(ROOT.kCyan-10)
hdR_j_h3.SetFillColor(ROOT.kCyan-8)
hdR_j_h4.SetFillColor(ROOT.kCyan-5)
hdR_j_h5.SetFillColor(ROOT.kYellow-8)
hdR_j_h6.SetFillColor(ROOT.kRed-4)
hdR_j_h7.SetFillColor(ROOT.kRed-5)
hdR_j_h8.SetFillColor(ROOT.kYellow+1)

hdR_j_h1.SetLineWidth(2)
hdR_j_h2.SetStats(0)
hdR_j_h2.SetTitle("#DeltaR Jets")
hdR_j_h2.GetXaxis().SetTitle("#DeltaR_{j1,j2}")
hdR_j_h2.GetYaxis().SetTitle("Normalized")
hdR_j_h2.GetYaxis().SetRangeUser(0,0.13)

hdR_j_h2.Draw("hist")
hdR_j_h3.Draw("hist same")
hdR_j_h4.Draw("hist same")
hdR_j_h5.Draw("hist same")
hdR_j_h6.Draw("hist same")
hdR_j_h7.Draw("hist same")
hdR_j_h8.Draw("hist same")
hdR_j_h1.Draw("hist same")

tex31 = ROOT.TLatex(0.153,0.92,"t#bar{t}t#bar{t}W Signal")
tex31.SetNDC()
tex31.SetTextAngle(0)
tex31.SetTextFont(42)
tex31.SetTextSize(0.04)
tex31.SetTextAlign(11)
tex31.Draw()

tex32 = ROOT.TLatex(0.730,0.92,"\sqrt{S} = {13TeV}")
tex32.SetNDC()
tex32.SetTextAngle(0)
tex32.SetTextFont(42)
tex32.SetTextAlign(11)
tex32.SetTextSize(0.04)
tex32.Draw()

legend16 = ROOT.TLegend(0.7, 0.7, 0.9, 0.85)
legend16.AddEntry(hdR_j_h1, "t#bar{t}t#bar{t}W", "l")
legend16.AddEntry(hdR_j_h2, "t#bar{t}", "f")
legend16.AddEntry(hdR_j_h3, "t#bar{t}H", "f")
legend16.AddEntry(hdR_j_h4, "t#bar{t}W", "f")
legend16.AddEntry(hdR_j_h5, "t#bar{t}Z", "f")
legend16.AddEntry(hdR_j_h6, "t#bar{t}t#bar{b}", "f")
legend16.AddEntry(hdR_j_h7, "t#bar{t}tW^{-}", "f")
legend16.AddEntry(hdR_j_h8, "t#bar{t}#bar{t}W^{+}", "f")
legend16.SetBorderSize(0)
legend16.Draw()

canvas16.Draw()
canvas16.SaveAs("tmva_bdt_variables_plots/deltaR_jets.png")

#----------------------------------------Delta R of B-Jets--------------------------------
hdR_bj_h1 = directory.Get("deltaR_bjets__Signal_Id")
hdR_bj_h2 = directory.Get("deltaR_bjets__tt~_Id")
hdR_bj_h3 = directory.Get("deltaR_bjets__tt~H_Id")
hdR_bj_h4 = directory.Get("deltaR_bjets__tt~W_Id")
hdR_bj_h5 = directory.Get("deltaR_bjets__tt~Z_Id")
hdR_bj_h6 = directory.Get("deltaR_bjets__tt~tb~_Id")
hdR_bj_h7 = directory.Get("deltaR_bjets__tt~tW-_Id")
hdR_bj_h8 = directory.Get("deltaR_bjets__tt~t~w+_Id")

#Scale the histograms by the cross sections
factor = 1.0
hdR_bj_h1.Scale(factor/hdR_bj_h1.Integral())
hdR_bj_h2.Scale(factor/hdR_bj_h2.Integral())
hdR_bj_h3.Scale(factor/hdR_bj_h3.Integral())
hdR_bj_h4.Scale(factor/hdR_bj_h4.Integral())
hdR_bj_h5.Scale(factor/hdR_bj_h5.Integral())
hdR_bj_h6.Scale(factor/hdR_bj_h6.Integral())
hdR_bj_h7.Scale(factor/hdR_bj_h7.Integral())
hdR_bj_h8.Scale(factor/hdR_bj_h8.Integral())

#Create a new canvas and draw the histograms
canvas17 = ROOT.TCanvas("canvas17", "#DeltaR B-Jets", 800, 600)
hdR_bj_h1.SetLineColor(ROOT.kBlack)
hdR_bj_h2.SetFillColor(ROOT.kCyan-10)
hdR_bj_h3.SetFillColor(ROOT.kCyan-8)
hdR_bj_h4.SetFillColor(ROOT.kCyan-5)
hdR_bj_h5.SetFillColor(ROOT.kYellow-8)
hdR_bj_h6.SetFillColor(ROOT.kRed-5)
hdR_bj_h7.SetFillColor(ROOT.kYellow+1)
hdR_bj_h8.SetFillColor(ROOT.kCyan-6)

hdR_bj_h1.SetLineWidth(2)
hdR_bj_h2.SetStats(0)
hdR_bj_h2.SetTitle("#DeltaR B-Jet")
hdR_bj_h2.GetXaxis().SetTitle("#DeltaR_{bj1,bj2}")
hdR_bj_h2.GetYaxis().SetTitle("Normalized")
hdR_bj_h2.GetYaxis().SetRangeUser(0, 0.10)

hdR_bj_h2.Draw("hist")
hdR_bj_h3.Draw("hist same")
hdR_bj_h4.Draw("hist same")
hdR_bj_h5.Draw("hist same")
hdR_bj_h6.Draw("hist same")
hdR_bj_h7.Draw("hist same")
hdR_bj_h8.Draw("hist same")
hdR_bj_h1.Draw("hist same")

tex33 = ROOT.TLatex(0.153,0.92,"t#bar{t}t#bar{t}W Signal")
tex33.SetNDC()
tex33.SetTextAngle(0)
tex33.SetTextFont(42)
tex33.SetTextSize(0.04)
tex33.SetTextAlign(11)
tex33.Draw()

tex34 = ROOT.TLatex(0.730,0.92,"\sqrt{S} = {13TeV}")
tex34.SetNDC()
tex34.SetTextAngle(0)
tex34.SetTextFont(42)
tex34.SetTextAlign(11)
tex34.SetTextSize(0.04)
tex34.Draw()

legend17 = ROOT.TLegend(0.7, 0.7, 0.9, 0.85)
legend17.AddEntry(hdR_bj_h1, "t#bar{t}t#bar{t}W", "l")
legend17.AddEntry(hdR_bj_h2, "t#bar{t}", "f")
legend17.AddEntry(hdR_bj_h3, "t#bar{t}H", "f")
legend17.AddEntry(hdR_bj_h4, "t#bar{t}W", "f")
legend17.AddEntry(hdR_bj_h5, "t#bar{t}Z", "f")
legend17.AddEntry(hdR_bj_h6, "t#bar{t}t#bar{b}", "f")
legend17.AddEntry(hdR_bj_h7, "t#bar{t}tW^{-}", "f")
legend17.AddEntry(hdR_bj_h8, "t#bar{t}#bar{t}W^{+}", "f")
legend17.SetBorderSize(0)
legend17.Draw()

canvas17.Draw()
canvas17.SaveAs("tmva_bdt_variables_plots/deltaR_bjets.png")

#----------------------------------------Missing Energy--------------------------------
hMissing_ET_h1 = directory.Get("missing_ET__Signal_Id")
hMissing_ET_h2 = directory.Get("missing_ET__tt~_Id")
hMissing_ET_h3 = directory.Get("missing_ET__tt~H_Id")
hMissing_ET_h4 = directory.Get("missing_ET__tt~W_Id")
hMissing_ET_h5 = directory.Get("missing_ET__tt~Z_Id")
hMissing_ET_h6 = directory.Get("missing_ET__tt~tb~_Id")
hMissing_ET_h7 = directory.Get("missing_ET__tt~tW-_Id")
hMissing_ET_h8 = directory.Get("missing_ET__tt~t~w+_Id")

#Scale the histograms by the cross sections
factor = 1.0
hMissing_ET_h1.Scale(factor/hMissing_ET_h1.Integral())
hMissing_ET_h2.Scale(factor/hMissing_ET_h2.Integral())
hMissing_ET_h3.Scale(factor/hMissing_ET_h3.Integral())
hMissing_ET_h4.Scale(factor/hMissing_ET_h4.Integral())
hMissing_ET_h5.Scale(factor/hMissing_ET_h5.Integral())
hMissing_ET_h6.Scale(factor/hMissing_ET_h6.Integral())
hMissing_ET_h7.Scale(factor/hMissing_ET_h7.Integral())
hMissing_ET_h8.Scale(factor/hMissing_ET_h8.Integral())

#Create a new canvas and draw the histograms
canvas18 = ROOT.TCanvas("canvas18", "#Missing ET", 800, 600)
hMissing_ET_h1.SetLineColor(ROOT.kBlack)
hMissing_ET_h2.SetFillColor(ROOT.kCyan-10)
hMissing_ET_h3.SetFillColor(ROOT.kCyan-8)
hMissing_ET_h4.SetFillColor(ROOT.kCyan-5)
hMissing_ET_h5.SetFillColor(ROOT.kYellow-8)
hMissing_ET_h6.SetFillColor(ROOT.kRed-4)
hMissing_ET_h7.SetFillColor(ROOT.kRed-5)
hMissing_ET_h8.SetFillColor(ROOT.kYellow+1)

hMissing_ET_h1.SetLineWidth(2)
hMissing_ET_h2.SetStats(0)
hMissing_ET_h2.SetTitle("Missing ET")
hMissing_ET_h2.GetXaxis().SetTitle("MET")
hMissing_ET_h2.GetYaxis().SetTitle("Normalized")
#hMissing_ET_h2.GetYaxis().SetRangeUser(0, 0.35)
#hMissing_ET_h2.GetXaxis().SetRangeUser(0, 150)

hMissing_ET_h2.Draw("hist")
hMissing_ET_h3.Draw("hist same")
hMissing_ET_h4.Draw("hist same")
hMissing_ET_h5.Draw("hist same")
hMissing_ET_h6.Draw("hist same")
hMissing_ET_h7.Draw("hist same")
hMissing_ET_h8.Draw("hist same")
hMissing_ET_h1.Draw("hist same")

tex33 = ROOT.TLatex(0.153,0.92,"t#bar{t}t#bar{t}W Signal")
tex33.SetNDC()
tex33.SetTextAngle(0)
tex33.SetTextFont(42)
tex33.SetTextSize(0.04)
tex33.SetTextAlign(11)
tex33.Draw()

tex34 = ROOT.TLatex(0.730,0.92,"\sqrt{S} = {13TeV}")
tex34.SetNDC()
tex34.SetTextAngle(0)
tex34.SetTextFont(42)
tex34.SetTextAlign(11)
tex34.SetTextSize(0.04)
tex34.Draw()

legend18 = ROOT.TLegend(0.7, 0.7, 0.9, 0.85)
legend18.AddEntry(hMissing_ET_h1, "t#bar{t}t#bar{t}W", "l")
legend18.AddEntry(hMissing_ET_h2, "t#bar{t}", "f")
legend18.AddEntry(hMissing_ET_h3, "t#bar{t}H", "f")
legend18.AddEntry(hMissing_ET_h4, "t#bar{t}W", "f")
legend18.AddEntry(hMissing_ET_h5, "t#bar{t}Z", "f")
legend18.AddEntry(hMissing_ET_h6, "t#bar{t}t#bar{b}", "f")
legend18.AddEntry(hMissing_ET_h7, "t#bar{t}tW^{-}", "f")
legend18.AddEntry(hMissing_ET_h8, "t#bar{t}#bar{t}W^{+}", "f")
legend18.SetBorderSize(0)
legend18.Draw()

canvas18.Draw()
canvas18.SaveAs("tmva_bdt_variables_plots/Missing_ET.png")

#----------------------------Ratio of the missing energy with sqrt(HT)--------------------------
hRatio_MET_HT_h1 = directory.Get("rat_MET_HT__Signal_Id")
hRatio_MET_HT_h2 = directory.Get("rat_MET_HT__tt~_Id")
hRatio_MET_HT_h3 = directory.Get("rat_MET_HT__tt~H_Id")
hRatio_MET_HT_h4 = directory.Get("rat_MET_HT__tt~W_Id")
hRatio_MET_HT_h5 = directory.Get("rat_MET_HT__tt~Z_Id")
hRatio_MET_HT_h6 = directory.Get("rat_MET_HT__tt~tb~_Id")
hRatio_MET_HT_h7 = directory.Get("rat_MET_HT__tt~tW-_Id")
hRatio_MET_HT_h8 = directory.Get("rat_MET_HT__tt~t~w+_Id")

#Scale the histograms by the cross sections
factor = 1.0
hRatio_MET_HT_h1.Scale(factor/hRatio_MET_HT_h1.Integral())
hRatio_MET_HT_h2.Scale(factor/hRatio_MET_HT_h2.Integral())
hRatio_MET_HT_h3.Scale(factor/hRatio_MET_HT_h3.Integral())
hRatio_MET_HT_h4.Scale(factor/hRatio_MET_HT_h4.Integral())
hRatio_MET_HT_h5.Scale(factor/hRatio_MET_HT_h5.Integral())
hRatio_MET_HT_h6.Scale(factor/hRatio_MET_HT_h6.Integral())
hRatio_MET_HT_h7.Scale(factor/hRatio_MET_HT_h7.Integral())
hRatio_MET_HT_h8.Scale(factor/hRatio_MET_HT_h8.Integral())

#Create a new canvas and draw the histograms
canvas19 = ROOT.TCanvas("canvas19", "#Ratio of MET with HT", 800, 600)
hRatio_MET_HT_h1.SetLineColor(ROOT.kBlack)
hRatio_MET_HT_h2.SetFillColor(ROOT.kCyan-10)
hRatio_MET_HT_h3.SetFillColor(ROOT.kCyan-8)
hRatio_MET_HT_h4.SetFillColor(ROOT.kCyan-5)
hRatio_MET_HT_h5.SetFillColor(ROOT.kYellow-8)
hRatio_MET_HT_h6.SetFillColor(ROOT.kRed-4)
hRatio_MET_HT_h7.SetFillColor(ROOT.kRed-5)
hRatio_MET_HT_h8.SetFillColor(ROOT.kYellow+1)

hRatio_MET_HT_h1.SetLineWidth(2)
hRatio_MET_HT_h2.SetStats(0)
hRatio_MET_HT_h2.SetTitle("MET/\\sqrt{HT}")
hRatio_MET_HT_h2.GetXaxis().SetTitle("MET/\\sqrt(HT)")
hRatio_MET_HT_h2.GetYaxis().SetTitle("Normalized")
#hRatio_MET_HT_h2.GetYaxis().SetRangeUser(0, 0.20)
#hRatio_MET_HT_h2.GetXaxis().SetRangeUser(0, 6)

hRatio_MET_HT_h2.Draw("hist")
hRatio_MET_HT_h3.Draw("hist same")
hRatio_MET_HT_h4.Draw("hist same")
hRatio_MET_HT_h5.Draw("hist same")
hRatio_MET_HT_h6.Draw("hist same")
hRatio_MET_HT_h7.Draw("hist same")
hRatio_MET_HT_h8.Draw("hist same")
hRatio_MET_HT_h1.Draw("hist same")

tex35 = ROOT.TLatex(0.153,0.92,"t#bar{t}t#bar{t}W Signal")
tex35.SetNDC()
tex35.SetTextAngle(0)
tex35.SetTextFont(42)
tex35.SetTextSize(0.04)
tex35.SetTextAlign(11)
tex35.Draw()

tex36 = ROOT.TLatex(0.730,0.92,"\sqrt{S} = {13TeV}")
tex36.SetNDC()
tex36.SetTextAngle(0)
tex36.SetTextFont(42)
tex36.SetTextAlign(11)
tex36.SetTextSize(0.04)
tex36.Draw()

legend19 = ROOT.TLegend(0.7, 0.7, 0.9, 0.85)
legend19.AddEntry(hRatio_MET_HT_h1, "t#bar{t}t#bar{t}W", "l")
legend19.AddEntry(hRatio_MET_HT_h2, "t#bar{t}", "f")
legend19.AddEntry(hRatio_MET_HT_h3, "t#bar{t}H", "f")
legend19.AddEntry(hRatio_MET_HT_h4, "t#bar{t}W", "f")
legend19.AddEntry(hRatio_MET_HT_h5, "t#bar{t}Z", "f")
legend19.AddEntry(hRatio_MET_HT_h6, "t#bar{t}t#bar{b}", "f")
legend19.AddEntry(hRatio_MET_HT_h7, "t#bar{t}tW^{-}", "f")
legend19.AddEntry(hRatio_MET_HT_h8, "t#bar{t}#bar{t}W^{+}", "f")
legend19.SetBorderSize(0)
legend19.Draw()

canvas19.Draw()
canvas19.SaveAs("tmva_bdt_variables_plots/Ratio_MET_HT.png")

#----------------------------Reconstructed Top Mass--------------------------
hM_top_h1 = directory.Get("top_mass__Signal_Id")
hM_top_h2 = directory.Get("top_mass__tt~_Id")
hM_top_h3 = directory.Get("top_mass__tt~H_Id")
hM_top_h4 = directory.Get("top_mass__tt~W_Id")
hM_top_h5 = directory.Get("top_mass__tt~Z_Id")
hM_top_h6 = directory.Get("top_mass__tt~tb~_Id")
hM_top_h7 = directory.Get("top_mass__tt~tW-_Id")
hM_top_h8 = directory.Get("top_mass__tt~t~w+_Id")

#Scale the histograms by the cross sections
factor = 1.0
hM_top_h1.Scale(factor/hM_top_h1.Integral())
hM_top_h2.Scale(factor/hM_top_h2.Integral())
hM_top_h3.Scale(factor/hM_top_h3.Integral())
hM_top_h4.Scale(factor/hM_top_h4.Integral())
hM_top_h5.Scale(factor/hM_top_h5.Integral())
hM_top_h6.Scale(factor/hM_top_h6.Integral())
hM_top_h7.Scale(factor/hM_top_h7.Integral())
hM_top_h8.Scale(factor/hM_top_h8.Integral())

#Create a new canvas and draw the histograms
canvas20 = ROOT.TCanvas("canvas20", "Recco Top Mass", 800, 600)
hM_top_h1.SetLineColor(ROOT.kBlack)
hM_top_h2.SetFillColor(ROOT.kCyan-10)
hM_top_h3.SetFillColor(ROOT.kCyan-8)
hM_top_h4.SetFillColor(ROOT.kYellow-8)
hM_top_h5.SetFillColor(ROOT.kRed-4)
hM_top_h6.SetFillColor(ROOT.kRed-5)
hM_top_h7.SetFillColor(ROOT.kYellow+1)
hM_top_h8.SetFillColor(ROOT.kCyan-6)

hM_top_h2.SetStats(0)
hM_top_h2.SetTitle("Reco Top Mass")
hM_top_h2.GetXaxis().SetTitle(" M_{t}^{reco}")
hM_top_h2.GetYaxis().SetTitle("Normalized")
hM_top_h2.GetYaxis().SetRangeUser(0, 0.23)
hM_top_h2.GetXaxis().SetRangeUser(0, 600)

hM_top_h2.Draw("hist")
hM_top_h3.Draw("hist same")
hM_top_h4.Draw("hist same")
hM_top_h5.Draw("hist same")
hM_top_h6.Draw("hist same")
hM_top_h7.Draw("hist same")
hM_top_h8.Draw("hist same")
hM_top_h1.Draw("hist same")
hM_top_h1.SetLineWidth(2)

tex37 = ROOT.TLatex(0.153,0.92,"t#bar{t}t#bar{t}W Signal")
tex37.SetNDC()
tex37.SetTextAngle(0)
tex37.SetTextFont(42)
tex37.SetTextSize(0.04)
tex37.SetTextAlign(11)
tex37.Draw()

tex38 = ROOT.TLatex(0.730,0.92,"\sqrt{S} = {13TeV}")
tex38.SetNDC()
tex38.SetTextAngle(0)
tex38.SetTextFont(42)
tex38.SetTextAlign(11)
tex38.SetTextSize(0.04)
tex38.Draw()

legend20 = ROOT.TLegend(0.7, 0.7, 0.9, 0.85)
legend20.AddEntry(hM_top_h1, "t#bar{t}t#bar{t}W", "l")
legend20.AddEntry(hM_top_h2, "t#bar{t}", "f")
legend20.AddEntry(hM_top_h3, "t#bar{t}Z", "f")
legend20.AddEntry(hM_top_h4, "t#bar{t}H", "f")
legend20.AddEntry(hM_top_h5, "t#bar{t}W", "f")
legend20.AddEntry(hM_top_h6, "t#bar{t}t#bar{b}", "f")
legend20.AddEntry(hM_top_h7, "t#bar{t}tW^{-}", "f")
legend20.AddEntry(hM_top_h8, "t#bar{t}#bar{t}W^{+}", "f")
legend20.SetBorderSize(0)
legend20.Draw()

canvas20.Draw()
canvas20.SaveAs("tmva_bdt_variables_plots/bdt_reco_topmass.png")

input("press enter to exit....")
#-------------------------------------------- *End* -----------------------------------
